const dailyBtn = document.querySelector("#daily")
const weeklyBtn = document.querySelector("#weekly")
const monthlyBtn = document.querySelector("#monthly")

const workDaily = document.querySelector(".work-container-daily")
const workWeekly = document.querySelector(".work-container-weekly")
const workMonthly = document.querySelector(".work-container-monthly")

const playDaily = document.querySelector(".play-container-daily")
const playWeekly = document.querySelector(".play-container-weekly")
const playMonthly = document.querySelector(".play-container-monthly")

const studyDaily = document.querySelector(".study-container-daily")
const studyWeekly = document.querySelector(".study-container-weekly")
const studyMonthly = document.querySelector(".study-container-monthly")

const excersiseDaily = document.querySelector(".excersise-container-daily")
const excersiseWeekly = document.querySelector(".excersise-container-weekly")
const excersiseMonthly = document.querySelector(".excersise-container-monthly")

const socialDaily = document.querySelector(".social-container-daily")
const socialWeekly = document.querySelector(".social-container-weekly")
const socialMonthly = document.querySelector(".social-container-monthly")

const selfcareDaily = document.querySelector(".selfcare-container-daily")
const selfcareWeekly = document.querySelector(".selfcare-container-weekly")
const selfcareMonthly = document.querySelector(".selfcare-container-monthly")

dailyBtn.addEventListener("click", () =>{
    workDaily.classList.remove("hidden")
    workWeekly.classList.add("hidden")
    workMonthly.classList.add("hidden")
    playDaily.classList.remove("hidden")
    playWeekly.classList.add("hidden")
    playMonthly.classList.add("hidden")
    studyDaily.classList.remove("hidden")
    studyWeekly.classList.add("hidden")
    studyMonthly.classList.add("hidden")
    excersiseDaily.classList.remove("hidden")
    excersiseWeekly.classList.add("hidden")
    excersiseMonthly.classList.add("hidden")
    socialDaily.classList.remove("hidden")
    socialWeekly.classList.add("hidden")
    socialMonthly.classList.add("hidden")
    selfcareDaily.classList.remove("hidden")
    selfcareWeekly.classList.add("hidden")
    selfcareMonthly.classList.add("hidden")
})

weeklyBtn.addEventListener("click", () =>{
    workDaily.classList.add("hidden")
    workWeekly.classList.remove("hidden")
    workMonthly.classList.add("hidden")
    playDaily.classList.add("hidden")
    playWeekly.classList.remove("hidden")
    playMonthly.classList.add("hidden")
    studyDaily.classList.add("hidden")
    studyWeekly.classList.remove("hidden")
    studyMonthly.classList.add("hidden")
    excersiseDaily.classList.add("hidden")
    excersiseWeekly.classList.remove("hidden")
    excersiseMonthly.classList.add("hidden")
    socialDaily.classList.add("hidden")
    socialWeekly.classList.remove("hidden")
    socialMonthly.classList.add("hidden")
    selfcareDaily.classList.add("hidden")
    selfcareWeekly.classList.remove("hidden")
    selfcareMonthly.classList.add("hidden")
})

monthlyBtn.addEventListener("click", () =>{
    workDaily.classList.add("hidden")
    workWeekly.classList.add("hidden")
    workMonthly.classList.remove("hidden")
    playDaily.classList.add("hidden")
    playWeekly.classList.add("hidden")
    playMonthly.classList.remove("hidden")
    studyDaily.classList.add("hidden")
    studyWeekly.classList.add("hidden")
    studyMonthly.classList.remove("hidden")
    excersiseDaily.classList.add("hidden")
    excersiseWeekly.classList.add("hidden")
    excersiseMonthly.classList.remove("hidden")
    socialDaily.classList.add("hidden")
    socialWeekly.classList.add("hidden")
    socialMonthly.classList.remove("hidden")
    selfcareDaily.classList.add("hidden")
    selfcareWeekly.classList.add("hidden")
    selfcareMonthly.classList.remove("hidden")
})